#!/usr/bin/env python3
"""Validate GPU reconstruction outputs against CPU reference.
Usage:
  python3 validate.py        # 256^3 outputs (default)
  python3 validate.py 512    # 512^3 outputs
"""
import sys
import numpy as np

try:
    import h5py
except ImportError:
    sys.exit("h5py not found: pip install h5py")

suffix = '_512' if (len(sys.argv) > 1 and sys.argv[1] == '512') else ''

FILES = {
    # python ref was hardcoded to the 256^3 file regardless of suffix, so
    # `validate.py 512` always compared against a 256^3-shaped array and
    # printed "shape mismatch" -- there was never a 512^3 python reference
    # to compare against in the first place. Now looks for
    # output_python_512.hdf5, generated by:
    #   python3 run_python_reference.py --data .../proj_512_75.hdf5 \
    #       --out output_python_512.hdf5 --epochs N
    'python':  f'output_python{suffix}.hdf5',
    'cpu':     f'output_cpu{suffix}.hdf5',
    'gpu-buf': f'output_gpu_buf{suffix}.hdf5',
    'gpu-img': f'output_gpu_img{suffix}.hdf5',
    'gpu-opt': f'output_gpu_opt{suffix}.hdf5',
}

def load(path):
    try:
        with h5py.File(path, 'r') as f:
            return f['Volume'][:]
    except FileNotFoundError:
        return None

def stats(v):
    return (np.nanmin(v), np.nanmax(v), np.nanmean(v),
            int(np.sum(np.isnan(v))), int(np.sum(np.isinf(v))))

volumes = {k: load(p) for k, p in FILES.items()}

ref = volumes.get('cpu')
if ref is None:
    sys.exit(f"{FILES['cpu']} not found — run cpu mode first")

py_ref = volumes.get('python')

label = "512^3" if suffix else "256^3"
print(f"\n=== {label} validation ===")
print(f"\n{'Mode':<10} {'min':>10} {'max':>10} {'mean':>10} {'nan':>6} {'inf':>6}  MSE vs CPU     MSE vs Python")
print("-" * 95)

for name, v in volumes.items():
    if v is None:
        if name == 'python':
            continue
        print(f"{name:<10}  [file not found]")
        continue

    mn, mx, me, nan_c, inf_c = stats(v)

    # python ref only comparable if shapes match
    py_ok = py_ref is not None and py_ref.shape == v.shape if v is not None else False

    if name == 'cpu':
        py_mse = ""
        if py_ok:
            m = np.mean((v.astype(np.float64) - py_ref.astype(np.float64))**2)
            py_mse = f"MSE={m:.3e}"
        elif py_ref is not None:
            py_mse = "shape mismatch"
        print(f"{name:<10} {mn:>10.4f} {mx:>10.4f} {me:>10.4f} {nan_c:>6} {inf_c:>6}  (reference)    {py_mse}")
    elif name == 'python':
        print(f"{name:<10} {mn:>10.4f} {mx:>10.4f} {me:>10.4f} {nan_c:>6} {inf_c:>6}  (python ref)   -")
    elif nan_c or inf_c:
        print(f"{name:<10} {mn:>10} {mx:>10} {me:>10} {nan_c:>6} {inf_c:>6}  DIVERGED")
    else:
        ref64 = ref.astype(np.float64)
        v64   = v.astype(np.float64)
        diff  = np.abs(v64 - ref64)
        mse   = np.mean(diff**2)
        maxd  = np.max(diff)
        cpu_str = f"MSE={mse:.3e}  max={maxd:.4f}"
        py_str = ""
        if py_ok:
            m = np.mean((v64 - py_ref.astype(np.float64))**2)
            py_str = f"MSE={m:.3e}"
        print(f"{name:<10} {mn:>10.4f} {mx:>10.4f} {me:>10.4f} {nan_c:>6} {inf_c:>6}  {cpu_str:<20} {py_str}")

        # outlier diagnostics: is max diff a handful of voxels (e.g. near a
        # geometric singularity where U->0 amplifies rounding via 1/U^2) or
        # widespread (systematic boundary-rule mismatch)?
        Nxz = v.shape[0]
        thresh = 10 * np.sqrt(mse) if mse > 0 else maxd * 0.5
        n_outliers = int(np.sum(diff > thresh))
        idx = np.unravel_index(np.argmax(diff), diff.shape)
        center = (Nxz - 1) / 2.0
        radial = np.sqrt(sum((idx[d] - center)**2 for d in range(2))) if len(idx) >= 2 else -1
        print(f"{'':10} outliers(diff>10*rms)={n_outliers}  worst_voxel_idx={idx}  "
              f"radial_dist_from_center_xy={radial:.1f} (Nxz/2={Nxz/2:.0f})")

print()
