#!/usr/bin/env python3
"""Validate GPU reconstruction outputs against CPU reference.
Usage:
  python3 validate.py            # 256^3 outputs in cwd (default)
  python3 validate.py 512        # 512^3 outputs in cwd
  python3 validate.py --dir submission_outputs/gtx680       # 256^3, different dir
  python3 validate.py 512 --dir submission_outputs/hawaii   # 512^3, different dir

--dir (or the VALIDATE_DIR env var) lets you point at an archived
results directory without copying files into cwd first -- useful when
working from a local checkout that doesn't have output_*.hdf5 sitting
at the repo root (those are only ever written there directly on the
actual GPU machines). Only works for submission_outputs/gtx680/, which
uses the same output_*.hdf5 naming as cwd -- submission_outputs/hawaii/
uses different filenames entirely (cpu_256.hdf5, not output_cpu.hdf5;
see plot_results.py's --source kale/pool15 distinction for the same
naming split) and isn't supported by this flag.
"""
import argparse
import os
import sys
import numpy as np

try:
    import h5py
except ImportError:
    sys.exit("h5py not found: pip install h5py")

parser = argparse.ArgumentParser(add_help=False)
parser.add_argument('scale', nargs='?', default='')
parser.add_argument('--dir', default=os.environ.get('VALIDATE_DIR', '.'))
args = parser.parse_args()

suffix = '_512' if args.scale == '512' else ''

def p(name):
    return os.path.join(args.dir, name)

FILES = {
    # Topic_2_CTreconstruction.py / Topic_2_CTreconstruction_512.py --
    # unmodified algorithm, random jitter, sample_ratio=1 (call-site
    # tunable, reduced from script default 2). What grading means by
    # "Reference code (python)". Each hardcodes its own dataset path, no
    # --data flag. 512^3 timing/feasibility unmeasured -- see the 512
    # script's own header and temp_scripts/topic2_512.sh.
    # Generated by: python3 Topic_2_CTreconstruction.py (256^3)
    #            or python3 Topic_2_CTreconstruction_512.py (512^3)
    'python_ref': p(f'output_python_reconstruction{suffix}.hdf5'),
    'cpu':        p(f'output_cpu{suffix}.hdf5'),
    'gpu-buf':    p(f'output_gpu_buf{suffix}.hdf5'),
    'gpu-img':    p(f'output_gpu_img{suffix}.hdf5'),
    'gpu-opt':    p(f'output_gpu_opt{suffix}.hdf5'),
}

def load(path):
    if path is None:
        return None
    try:
        with h5py.File(path, 'r') as f:
            return f['Volume'][:]
    except FileNotFoundError:
        return None

def stats(v):
    return (np.nanmin(v), np.nanmax(v), np.nanmean(v),
            int(np.sum(np.isnan(v))), int(np.sum(np.isinf(v))))

volumes = {k: load(p) for k, p in FILES.items()}

ref = volumes.get('cpu')
if ref is None:
    sys.exit(f"{FILES['cpu']} not found — run cpu mode first")

python_ref = volumes.get('python_ref')

label = "512^3" if suffix else "256^3"
print(f"\n=== {label} validation ===")
print(f"\n{'Mode':<10} {'min':>10} {'max':>10} {'mean':>10} {'nan':>6} {'inf':>6}  MSE vs CPU     MSE vs Python Ref")
print("-" * 100)

for name, v in volumes.items():
    if v is None:
        if name == 'python_ref':
            continue
        print(f"{name:<10}  [file not found]")
        continue

    mn, mx, me, nan_c, inf_c = stats(v)

    # python_ref reference only comparable if shapes match
    pref_ok = python_ref is not None and python_ref.shape == v.shape if v is not None else False

    if name == 'cpu':
        pref_mse = ""
        if pref_ok:
            m = np.mean((v.astype(np.float64) - python_ref.astype(np.float64))**2)
            pref_mse = f"MSE={m:.3e}"
        elif python_ref is not None:
            pref_mse = "shape mismatch"
        print(f"{name:<10} {mn:>10.4f} {mx:>10.4f} {me:>10.4f} {nan_c:>6} {inf_c:>6}  (reference)    {pref_mse}")
    elif name == 'python_ref':
        print(f"{name:<10} {mn:>10.4f} {mx:>10.4f} {me:>10.4f} {nan_c:>6} {inf_c:>6}  (python ref)")
    elif nan_c or inf_c:
        print(f"{name:<10} {mn:>10} {mx:>10} {me:>10} {nan_c:>6} {inf_c:>6}  DIVERGED")
    else:
        ref64 = ref.astype(np.float64)
        v64   = v.astype(np.float64)
        diff  = np.abs(v64 - ref64)
        mse   = np.mean(diff**2)
        maxd  = np.max(diff)
        cpu_str = f"MSE={mse:.3e}  max={maxd:.4f}"
        pref_str = ""
        if pref_ok:
            m = np.mean((v64 - python_ref.astype(np.float64))**2)
            pref_str = f"MSE={m:.3e}"
        print(f"{name:<10} {mn:>10.4f} {mx:>10.4f} {me:>10.4f} {nan_c:>6} {inf_c:>6}  {cpu_str:<20} {pref_str}")

        # outlier diagnostics: is max diff a handful of voxels or widespread
        # (systematic boundary-rule mismatch)?
        #
        # NOTE: this used to claim the outliers sat near a geometric
        # singularity (U->0 amplifying rounding via 1/U^2). That was checked
        # directly with diag_maxgap.py at 256^3 and is FALSE: at the actual
        # worst voxel, min|U| over all 75 angles is 4.10 = 82% of SOD, and
        # 1/U^2 is only 1.5x its isocentre value. The real pattern is a
        # one-voxel spatial displacement of sharp features in gpu-img/gpu-opt
        # (hardware CLK_FILTER_LINEAR sampling) vs cpu/gpu-buf (manual
        # float32 trilinear) -- mass is conserved across the neighbouring
        # voxel pair, so it is a sampler-precision edge effect, not a
        # magnitude error. All half-texel (+0.5f) offsets were audited and
        # are correct in every kernel, so it is not a coordinate-origin bug.
        Nxz = v.shape[0]
        thresh = 10 * np.sqrt(mse) if mse > 0 else maxd * 0.5
        n_outliers = int(np.sum(diff > thresh))
        idx = np.unravel_index(np.argmax(diff), diff.shape)
        center = (Nxz - 1) / 2.0
        radial = np.sqrt(sum((idx[d] - center)**2 for d in range(2))) if len(idx) >= 2 else -1
        print(f"{'':10} outliers(diff>10*rms)={n_outliers}  worst_voxel_idx={idx}  "
              f"radial_dist_from_center_xy={radial:.1f} (Nxz/2={Nxz/2:.0f})")

print()
